#!/bin/bash
inotifywait -m -r /usr/local/freeswitch/recordings/cc-test-telephony/ -e close_write | while read path action file;
do
echo "The file '$file' appeared in directory '$path' via '$action'"
aws s3 mv $path/$file s3://cc-test-telephony/recordings/$file
echo $a
done
